industry_keywords:
  农林牧渔: ["农业", "粮食", "种业", "畜牧", "渔业", "养殖"]
  基础化工: ["化工", "化学", "原料", "化肥", "农药", "化纤", "塑料"]
  钢铁: ["钢铁", "钢材", "粗钢", "生铁", "铁矿"]
  有色金属: ["有色", "铜", "铝", "锌", "镍", "稀土"]
  电子: ["电子", "半导体", "芯片", "集成电路", "面板"]
  汽车: ["汽车", "新能源车", "电动车", "汽车产业链"]
  家用电器: ["家电", "空调", "冰箱", "洗衣机"]
  食品饮料: ["食品", "饮料", "白酒", "啤酒", "乳制品"]
  纺织服饰: ["纺织", "服装", "纺服", "鞋帽"]
  轻工制造: ["轻工", "包装", "造纸", "家具", "文具"]
  医药生物: ["医药", "药品", "生物医药", "疫苗", "医疗器械"]
  公用事业: ["公用事业", "水务", "燃气", "电力运营"]
  交通运输: ["交通运输", "物流", "港口", "航运", "铁路", "航空"]
  房地产: ["房地产", "地产", "房企", "住房"]
  商贸零售: ["零售", "商贸", "超市", "电商"]
  社会服务: ["旅游", "酒店", "服务业", "餐饮"]
  银行: ["银行", "信贷", "存款", "贷款"]
  非银金融: ["券商", "保险", "信托", "资管", "期货"]
  综合: ["综合", "多元化"]
  建筑材料: ["建材", "水泥", "玻璃", "石灰"]
  建筑装饰: ["基建", "建筑", "装饰", "工程"]
  电力设备: ["电力设备", "电网", "输变电", "光伏", "风电", "储能", "电气"]
  机械设备: ["机械", "装备", "机床", "机器人", "设备制造"]
  国防军工: ["军工", "航天", "航空", "舰船", "武器", "导弹"]
  计算机: ["计算机", "软件", "人工智能", "云计算", "大数据"]
  传媒: ["传媒", "广告", "影视", "游戏", "出版"]
  通信: ["通信", "5G", "运营商", "光纤"]
  煤炭: ["煤炭", "煤矿", "焦煤", "动力煤"]
  石油石化: ["石油", "原油", "石化", "炼油", "天然气"]
  环保: ["环保", "治理", "污水", "固废", "碳中和"]
  美容护理: ["美容", "护理", "医美"]
